library(lubridate)
library(ggplot2)
library(tidyverse)

list.files("data")

atlanta      <- read_csv("data/atlanta.csv")
boston       <- read_csv("boston.csv")
charlotte    <- read_csv("charlotte.csv")
chicago      <- read_csv("chicago.csv")
detroit      <- read_csv("detroit.csv")
la           <- read_csv("la.csv")
miami        <- read_csv("miami.csv")
minneapolis  <- read_csv("minneapolis.csv")
montgomery   <- read_csv("montgomery.csv")
newjersey    <- read_csv("newjersey.csv")
newyork      <- read_csv("newyork.csv")
philly       <- read_csv("philly.csv")
phoenix      <- read_csv("phoenix.csv")
saltlakecity <- read_csv("saltlakecity.csv")
seattle      <- read_csv("seattle.csv")
stlouis      <- read_csv("stlouis.csv")